import {
  AlertTriangle,
  ArrowRight,
  BarChart,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  Clipboard,
  Copy,
  Edit3,
  FileText,
  HelpCircle,
  Image as ImageIcon,
  Link as LinkIcon,
  Loader2,
  LogIn,
  LogOut,
  MessageSquare,
  Moon,
  PlusCircle,
  Send,
  Settings,
  Sheet,
  Sun,
  Trash2,
  User,
  XCircle,
  Github,
  Bot,
  Wand2,
  Table,
  Database
} from "lucide-react";

export const Icons = {
  alertTriangle: AlertTriangle,
  arrowRight: ArrowRight,
  barChart: BarChart,
  bot: Bot,
  checkCircle: CheckCircle,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clipboard: Clipboard,
  copy: Copy,
  database: Database,
  edit3: Edit3,
  fileText: FileText,
  github: Github,
  helpCircle: HelpCircle,
  image: ImageIcon,
  link: LinkIcon,
  loader: Loader2,
  logIn: LogIn,
  logOut: LogOut,
  messageSquare: MessageSquare,
  moon: Moon,
  plusCircle: PlusCircle,
  send: Send,
  settings: Settings,
  sheet: Sheet,
  sun: Sun,
  table: Table,
  trash2: Trash2,
  user: User,
  wand: Wand2,
  xCircle: XCircle,
};

export type IconKey = keyof typeof Icons;
